with-expecter: true
packages:
  github.com/openmfp/account-operator/pkg/service:
    config:
      dir: pkg/subroutines/mocks
      outpkg: mocks
    interfaces:
      Service:
        config:
          mockname: K8Service

  # third party
  github.com/openfga/api/proto/openfga/v1:
    config:
      dir: pkg/subroutines/mocks
      outpkg: mocks
    interfaces:
      OpenFGAServiceClient:
        config:
          mockname: OpenFGAServiceClient

