---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.openmfp.io
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openmfp.io
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - core.openmfp.io
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
