apiVersion: core.openmfp.io/v1alpha1
kind: Store
metadata:
  labels:
    app.kubernetes.io/name: openfga-modular-modules-operator
    app.kubernetes.io/managed-by: kustomize
  name: sap
spec:
  coreModule:
    name: core
