apiVersion: core.openmfp.io/v1alpha1
kind: Account
metadata:
  name: new-account-debug
  namespace: default
spec:
  accountRole: Folder
  displayName: New Demo Account
  creator: bastian.echterhoelter@sap.com