apiVersion: core.openmfp.io/v1alpha1
kind: Account
metadata:
  labels:
    app.kubernetes.io/name: account-operator
    app.kubernetes.io/managed-by: kustomize
  name: account-sample
spec:
  # TODO(user): Add fields here
