apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.openmfp.org
spec:
  latestResourceSchemas:
  - v250220-cdcd05c.accounts.core.openmfp.org
  - v250224-cafdd19.accountinfos.core.openmfp.org
status: {}
