name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  download-kcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: kcp-dev/kcp
          ref: main
          path: kcp
      - name: Run build script
        working-directory: kcp
        run: |
          IGNORE_GO_VERSION=1  make build

  pipe:
    needs: download-kcp
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-golang-app.yml@main
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/account-operator
      useTask: true
      useLocalCoverageConfig: true
      repoVersionUpdate: openmfp/helm-charts
      coverageThreasholdTotal: 92
