name: ci
on: [push]

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-golang-app.yml@feat/allow-local-coverage-configuration
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/account-operator
      useMake: true
